---
- name: Install necessary packages
  apt: pkg={{ item }} state=present
  with_items:
  - ltsp-server
  - ldm
  - ldm-server

- name: Check for image file
  stat: path=/opt/ltsp/i386
  register: image
  
- name: Build ltsp client image
  debug: msg="Initial image will be built"
  notify: ltsp-image-initial
  when: image.stat.exists == False

- name: Update lstp client image
  debug: msg="Existing image will be updated"
  notify: ltsp-image-update
  when: image.stat.exists == True
