---
- name: Install necessary packages
  apt: pkg={{ item }} state=present
  with_items:
  - ltsp-server
  - ldm
  - ldm-server

- name: Check for image file
  stat: path=/opt/ltsp/i386
  register: image
  
- name: Build ltsp client image
  command: ltsp-build-client --arch i386
  when: image.stat.exists == False
