---
- name: Add greek repo
  apt_repository: repo=ppa:ts.sch.gr state=present update_cache=yes

- name: Install necessary packages
  apt: pkg={{ item }} state=present
  with_items:
  - ltsp-server
  - ltsp-client
  - ldm
  - ldm-server

- name: Check for image file
  stat: path=/opt/ltsp/i386
  register: image
  
- name: Build ltsp client image
  command: /bin/true
  notify: ltsp-image-initial
  when: image.stat.exists == False

- name: Update lstp client image
  command: /bin/true
  notify: ltsp-image-update
  when: image.stat.exists == True
