---
- name: Install necessary packages
  apt: pkg={{ item }} state=present
  with_items:
  - ltsp-server
  - ldm
  - ldm-server

- name: Install graphical environments
  apt: pkg={{ item }} state=present
  with_items: "{{ gfx_envs }}"

- name: Build ltsp client image
  command: ltsp-build-client --arch i386